Incorrect stack trace for stripped binaries
google/glog pull request #1092
Opened 2024-04-01 15:28 UTC by xppt

If the executable is stripped, I expect the `FailureSignalHandler` to dump module+offset for each stack frame, but the output is always `(unknown)`.
Seems like this is because of a typo in `OpenObjectFileContainingPcAndGetStartAddress`.

Code to reproduce:
[repro.zip](https://github.com/google/glog/files/14825377/repro.zip)
Just run `./run_test.py` (docker and python3 are required).

2024-04-02 12:30 UTC, sergiud requested changes
Thanks for the PR! I have one minor remark.

Also, what's the output with your changes?

2024-04-02 12:30 UTC, sergiud commented on src/symbolize.cc
>      if (!object_fd) {
```suggestion
    return FileDescriptor{FailureRetry([cursor] { return open(cursor, O_RDONLY); })};
```
`object_fd` can be returned directly.

2024-04-02 12:43 UTC, xppt commented on src/symbolize.cc
>      if (!object_fd) {
Thanks, I've applied the patch.

2024-04-02 12:44 UTC, xppt commented
> Also, what's the output with your changes?

The stack trace contains module+offset line after patching:
```
    @     0x7fde6810f699 __cxa_throw
    @     0x55ce95d3d389 (/build/testbin-stripped+0x2388)
    @     0x55ce95d3d3c6 main
```

2024-04-22 18:57 UTC, sergiud approved these changes

2024-04-22 19:08 UTC, sergiud commented
Thank you!

2024-04-22 19:08 UTC, merged