truncate single file upon creation
google/glog pull request #1143
Opened 2024-12-16 09:54 UTC by HNOONa-0

A small change that writes logs to beginning of the file when its size exceeds `max_log_size` constraint.

Fixes: #1089

2024-12-16 10:10 UTC, HNOONa-0 commented
@sergiud PTAL!

2025-01-19 16:34 UTC, sergiud commented
Thanks for the PR and apologies for the late reply.

I'm not sure I understand the change. The log output file is truncated unconditionally; no check against `max_log_size` is performed. Can you elaborate why this still fixes the issue?

2025-01-19 16:52 UTC, sergiud requested changes

2025-01-19 16:52 UTC, sergiud commented on src/logging.cc
> +    flags = flags | O_TRUNC;
It would be nice to have a unit test for this change to avoid regressions.

2025-01-19 19:30 UTC, HNOONa-0 commented
> Thanks for the PR and apologies for the late reply.
> 
> I'm not sure I understand the change. The log output file is truncated unconditionally; no check against `max_log_size` is performed. Can you elaborate why this still fixes the issue?

There are two scenarios:
If `FLAGS_timestamp_in_logfile_name` is true, then a new file with a timestamp is created.

Else, it's implied that we are writing to a single log file, and in this case, whenever we are attempting to create a new file, it's because:
1. The log file is created for the first time.
2. The log file is being recreated due to length overflow in file size in this part of implementation:
https://github.com/google/glog/blob/6c5c692c8e423f651c74de9477ff0b5a59008bcc/src/logging.cc#L1110-L1117

In both these scenarios, the file should be truncated to reset the file size, hence the `O_TRUNC` flag. Is my understanding correct so far?

2025-01-19 20:53 UTC, sergiud commented
I see, thanks. Could you please extend the comment to mention that the log is recreated in the `else` branch due to size overflow as per 2?

2025-01-22 18:15 UTC, HNOONa-0 commented
Hey @sergiud!
I’ve extended the comments as you suggested and added a new test method to validate these changes. In this test, I turned off the `timestamp` flag and constrained the `log_size` to 1MB. Then, I logged `2e4` lines. Although the total lines exceed the `1MB` threshold, the test ensures that the file size remains within the `1MB` limit.

2025-02-20 13:46 UTC, HNOONa-0 commented
Hey @sergiud, sorry for the delay.
I've made a few changes to allow appending when the file isn't at max size, along with some minor refactoring.
The tests should pass hopefully.

2025-02-20 16:47 UTC, sergiud commented
Thanks!

2025-02-20 16:49 UTC, merged