Add LWP id to dump info
google/glog pull request #1146
Opened 2024-12-19 05:03 UTC by stdpain

LWP can help gdb find the corresponding thread more quickly.

2025-01-19 16:22 UTC, sergiud requested changes
Thanks for the PR and apologies for the late reply.

Please see my remarks.

2025-01-19 16:22 UTC, sergiud commented on src/signalhandler.cc
> +  formatter.AppendString("(LWP ");
Please surround the LWP by previously opened braces.

2025-01-19 16:22 UTC, sergiud commented on src/signalhandler.cc
> +#  include <sys/syscall.h>
The availability of a POSIX header (`unistd.h`) does not imply the availability of LInux headers. Please use the appropriate config macros (i.e., `HAVE_SYS_SYSCALL_H`, etc.) here.

2025-01-21 19:20 UTC, sergiud commented on src/signalhandler.cc
> +  pid_t tid = syscall(SYS_gettid);
Unfortunately, using `syscall` triggers the following error on macOS caused by a deprecation warning:
```console
src/signalhandler.cc:224:15: error: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Werror,-Wdeprecated-declarations]
  pid_t tid = syscall(SYS_gettid);
```
We try to avoid deprecated APIs.

2025-01-22 03:43 UTC, stdpain commented on src/signalhandler.cc
> +  pid_t tid = syscall(SYS_gettid);
change to: print LWP id only on Linux platforms

2025-02-16 14:50 UTC, sergiud commented
Thanks!

2025-02-16 14:51 UTC, sergiud approved these changes

2025-02-16 14:51 UTC, merged