CHECK support for nullptr (fixes #341)
google/glog pull request #641
Opened 2021-04-08 21:52 UTC by sergiud

This allows `CHECK_NE(foo, nullptr)` to compile and produces "nullptr" for the string representation of `nullptr`.

Finalizes #342

Closes #562 #341

2021-04-09 07:26 UTC, drigz requested changes
Thanks! Could you also add -DHAVE_CXX11_NULLPTR_T to common_copts in bazel/glog.bzl?

2021-04-09 08:26 UTC, sergiud commented
@drigz In that case, `ac_cv_cxx11_nullptr_t` should also be set to 1 in `common_config`, correct?

2021-04-09 08:42 UTC, drigz commented
> @drigz In that case, ac_cv_cxx11_nullptr_t should also be set to 1 in common_config, correct?

Ah, I misread and thought that it was set to 1, sorry. Either approach is OK, in that case, but I have a slight preference for assuming a modern environment in the Bazel build: I think that people with weird environments use build systems with environment detection, and Bazel users are expecting the modern features.

2021-04-12 07:26 UTC, drigz approved these changes
Thanks!

2021-04-12 08:08 UTC, merged