Make LogCleaner support relative paths
google/glog pull request #654
Opened 2021-05-18 04:30 UTC by aesophor

Closes #653 

In #653, the user reports that the following usage of glog API:
```cpp
google::SetLogDestination(google::INFO, ".");
google::EnableLogCleaner(1);
```

will lead to an uncaught out_of_range exception.
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 0)
[1]    835009 abort (core dumped)  ./out
```

This is caused by a bug in `LogCleaner::Run()` where `base_filename` doesn't end with a "/".
https://github.com/google/glog/blob/0b3d4cb471e36d8e677e75e4e8d0345e7bf2a418/src/logging.cc#L1334-L1335

This PR:
1. checks if `base_filename` in `LogCleaner::Run()` ends with a "/", and if not, then we simply pass the relative path to `LogCleaner::GetOverdueLogNames()`.
2. In `LogCleaner::GetOverdueLogNames`, we only concatenate `log_directory` and `ent->d_name` if `log_directory` ends with a "/". Otherwise, just pass the relative path to `LogCleaner::IsLogFromCurrentProject`.
3. Some trivial changes to improve the readability of source code

2021-05-18 04:47 UTC, aesophor commented
@sergiud @jixianliu1234

I've also discovered this:

```cpp
google::SetLogDestination(google::INFO, "./");  // creates logs under process's cwd
                                                // example: 20210518-122553.954758

google::SetLogDestination(google::INFO, ".");   // also creates logs under process's cwd, but filenames starts with "."
                                                // example: .20210518-122537.954584
```

Another example:
```cpp
google::SetLogDestination(google::INFO, "/tmp/");  // creates logs under /tmp/
google::SetLogDestination(google::INFO, "/tmp");   // creates logs under / with filenames starting with "tmp"
```

<br>

Therefore, I think the correct way of setting log destination to "." is `google::SetLogDestination(google::INFO, "./");`.
Maybe this should be documented somewhere (please tell me if I missed it in the documentation)

Thanks.

2021-05-23 19:45 UTC, sergiud requested changes
I believe there should be no difference between
```cpp
google::SetLogDestination(google::INFO, "./");
```
and
```cpp
google::SetLogDestination(google::INFO, ".");
```
since `.` and `./` are both directories.

2021-05-23 19:45 UTC, sergiud commented on src/logging.cc
> +      if (log_directory.at(log_directory.size() - 1) == dir_delim_) {
`at` throws on out of range access. This should be avoided.

2021-05-23 19:45 UTC, sergiud commented on src/logging.cc
> +    if (i <= cleaned_base_filename.size() + 7) {  // 0 ~ 7 : YYYYMMDD
These formatting changes seem to be unrelated. I would undo them.

2021-07-14 17:59 UTC, sergiud commented
Any progress?

2021-10-29 21:13 UTC, sergiud approved these changes

2021-10-29 21:14 UTC, merged