Fix syscall deprecation warning on macOS >= 10.12 (#1)
google/glog pull request #685
Opened 2021-07-13 11:51 UTC by z-aki

Fix #185

2021-07-13 11:55 UTC, z-aki commented
@googlebot I signed it!

2021-07-13 12:07 UTC, sergiud requested changes
Currently, it is not possible to test these changes as a corresponding Mac OS X Github workflow is missing.

2021-07-13 12:07 UTC, sergiud commented on src/utilities.cc
> +#if (defined OS_MACOSX && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_12)
```suggestion
#if (defined(OS_MACOSX) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_12)
```

2021-07-13 12:07 UTC, sergiud commented on src/raw_logging.cc
> +  !(defined OS_MACOSX && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_12)
```suggestion
  !(defined(OS_MACOSX) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_12)
```

2021-07-13 13:56 UTC, z-aki commented
Err is that failure my fault ? macOS guards shouldn't affect mingw..

2021-07-13 13:59 UTC, sergiud commented
The failure is very likely caused by this branch.

2021-07-13 14:01 UTC, z-aki commented
Okay, so far I was building glog as part of a downstream project. 
Will check separately now.

2021-07-13 15:15 UTC, z-aki commented
Okay it was operator precedence. Fixed now.

2021-07-14 08:40 UTC, sergiud commented
Thanks. Could you please rebase onto current master? CI now supports macOS.

2021-07-14 10:41 UTC, sergiud commented
macOS builds still issue a warning, e.g.,
```
/Users/runner/work/glog/glog/src/raw_logging.cc:140:3: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface
```

2021-07-14 11:15 UTC, sergiud commented
Warning still present.

2021-07-14 11:17 UTC, z-aki commented
Shouldn't the glog project be defining  `MAC_OS_X_VERSION_MAX_ALLOWED` since you know which OSes it will be build on? 
If you can't I can just remove the macOS version stuff and make it dependent on OS only.

2021-07-14 11:28 UTC, sergiud commented
The library doesn't care about `MAC_OS_X_VERSION_MAX_ALLOWED`, hence it does need to be defined.

Can't you just check the presence of `pthread_threadid_np` in CMake using `check_function_exists` and use the function if it is available instead of relying on defines?

2021-07-14 12:09 UTC, sergiud requested changes

2021-07-14 12:09 UTC, sergiud commented on src/config.h.cmake.in
> +#cmakedefine HAVE_PTHREAD_THREADID_NP ${HAVE_PTHREAD_THREADID_NP}
Please add a comment describing the define for consistency.

2021-07-14 12:09 UTC, sergiud commented on CMakeLists.txt
> +check_symbol_exists (pthread_threadid_np "pthread.h" HAVE_PTHREAD_THREADID_NP)
```suggestion
cmake_push_check_state (RESET)
set (CMAKE_REQUIRED_LIBRARIES Threads::Threads)
check_cxx_symbol_exists (pthread_threadid_np pthread.h HAVE_PTHREAD_THREADID_NP)
cmake_pop_check_state ()
```

2021-07-14 12:09 UTC, sergiud commented on CMakeLists.txt
> +check_cxx_source_compiles ("
This is unnecessary.

2021-07-14 12:33 UTC, z-aki commented
nope warning's still there..
It's sometimes useful to clear cache when dealing with cmake variables.
Also, in one of the older attempts, I just set the code to 
```
#if (defined(OS_MACOSX))
    uint64_t tid64;
    pthread_threadid_np(NULL, &tid64);
    pid_t tid = (pid_t)tid64;
...
```
and it built fine. 
The function was introduced in macOS 10.6 so seems safe to use now.

2021-07-14 13:37 UTC, sergiud requested changes
I have just one minor remark. You can then squash the commits.

2021-07-14 13:37 UTC, sergiud commented on src/utilities.cc
> +    pthread_threadid_np(NULL, &tid64);
You should probably check the return value and assign -1 to `tid` in case of an error.

2021-07-14 15:49 UTC, sergiud approved these changes

2021-07-14 15:49 UTC, sergiud commented
Great. Thanks!

2021-07-14 15:49 UTC, merged