simplify DLOG macro definition in NDEBUG mode
google/glog pull request #830
Opened 2022-06-06 14:03 UTC by lstaroth

Simplify the DLOG macro definition in NDEBUG mode with consistent logic

2022-08-01 08:59 UTC, sergiud requested changes
Thanks for the PR. I have some minor remarks. Could you also please rebase?

2022-08-01 08:59 UTC, sergiud commented on src/glog/logging.h.in
> +#define DLOG(severity) if(false) LOG(severity)
```suggestion
#define DLOG(severity) if((false)) LOG(severity)
```
To avoid warnings due to constant condition.

2022-08-01 08:59 UTC, sergiud commented on src/glog/logging.h.in
> +#define DVLOG(verboselevel) if(false && VLOG_IS_ON(verboselevel)) LOG(INFO)
```suggestion
#define DVLOG(verboselevel) if((false) && VLOG_IS_ON(verboselevel)) LOG(INFO)
```
Is the `VLOG_IS_ON` check even necessary?

2022-08-01 08:59 UTC, sergiud commented on src/glog/logging.h.in
> +#define DLOG_IF(severity, condition) if(false && (condition)) LOG(severity)
```suggestion
#define DLOG_IF(severity, condition) if((false) && (condition)) LOG(severity)
```
As before, why is the `condition` check needed here?

2022-08-01 08:59 UTC, sergiud commented on src/glog/logging.h.in
> +#define DLOG_EVERY_N(severity, n) if(false) LOG(severity)
```suggestion
#define DLOG_EVERY_N(severity, n) if((false)) LOG(severity)
```

2022-08-01 08:59 UTC, sergiud commented on src/glog/logging.h.in
> +#define DLOG_IF_EVERY_N(severity, condition, n) if(false && (condition)) LOG(severity)
```suggestion
#define DLOG_IF_EVERY_N(severity, condition, n) if((false) && (condition)) LOG(severity)
```

2022-08-01 08:59 UTC, sergiud commented on src/glog/logging.h.in
> +#define DLOG_ASSERT(condition) if(false) LOG_ASSERT(condition)
```suggestion
#define DLOG_ASSERT(condition) if((false)) LOG_ASSERT(condition)
```

2022-08-06 17:43 UTC, lstaroth commented
@sergiud Thank you for your suggestions, I have edited it

2022-08-06 18:32 UTC, sergiud approved these changes

2022-08-06 18:32 UTC, sergiud commented
Thanks!

2022-08-06 18:33 UTC, merged